[package]
name = "idp-proto"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["cdylib", "lib"]
crate-name = "idp-proto"

[features]
default = ["client"]
uniffi = ["dep:uniffi"]
client = []
server = []

[dependencies]
bitcode = "0.6.9"
cuid2 = "0.1.6"
hex = "0.4.3"
pastey = "0.2.3"
snafu = { version = "0.9.2", features = ["unstable-provider-api"] }
xxhash-rust = { version = "0.8.18", features = ["const_xxh3"] }
tracing = "0.1.44"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
rustls = { version = "0.23.45"  }
rustls-pemfile = { version = "2.2.0" }
tokio-rustls = { version = "0.26.5" }
uniffi = { version = "0.32.1", optional = true, features = ["cli"] }
tokio = { version = "1.53.1", features = ["net", "sync", "rt", "io-util"] }
getrandom = "0.4.3"

[target.'cfg(target_family = "wasm")'.dependencies]
xwt-core = "0.10.0"
xwt-web = "0.22.1"
wasm-bindgen = "0.2.128"
wasm-bindgen-futures = "0.4.78"
strum = { version = "0.28.0", features = ["derive"] }
tokio = { version = "1.53.1", features = ["sync", "io-util"] }
getrandom = { version = "0.4.3", features = ["wasm_js"] }

[build-dependencies]
uniffi = { version = "0.32.1", features = ["build"] }
